from robotKinematics.inverseKinematics.__4DOF.__palletizing.ABB_IRB260 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.ABB_IRB460 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.ABB_IRB660_180 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.ABB_IRB660_250 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.ABB_IRB760 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Comau_Smart5_PAL_180 import * # FK does not work 100%. IK not at all
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Comau_Smart5_PAL_260 import * # FK does not work 100%. IK not at all
from robotKinematics.inverseKinematics.__4DOF.__palletizing.DobotMagician import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.DobotMagicianLite import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.DobotMG400 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Fanuc_M410iB_300 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Fanuc_M410iB_700 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Fanuc_M410iC_185 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.GSK_RMD08 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_40_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_100_2_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_120_R3200_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_140_R3200_2_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_180_R3200_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_180_R3200_2_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_180_2_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_240_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_240_R3200_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.KUKA_KR_700_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Leantec_LP1520_12_C import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.RoboDK_RDK_2100_PA import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.uFactory_uArm import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_EPL160 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_MPK50 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_MPL300 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_MPL800 import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_MPL800II import *
from robotKinematics.inverseKinematics.__4DOF.__palletizing.Motoman_PL190 import *