from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR3 import UR3
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR5 import UR5
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR5e import UR5e
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR10 import UR10
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR10e import UR10e
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR16e import UR16e
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR20 import UR20
from robotKinematics.inverseKinematics.__6DOF.__UniversalRobots.UR30 import UR30