from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_CRB_1300_7_14 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_CRB_1300_10_115 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_CRB_1300_11_09 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_CRB_15000 import * # a6
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_120 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_140 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_580_12S import * # theta5 = 35* & theta6 = -35*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_580_16 import * # theta5 = 35* & theta6 = -35*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1010_15_037 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1100_4_058 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1100_4_0475 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1200_5_09 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1200_7_07 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1300_7_14 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1300_10_115 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1300_11_09 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1410_4_145 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1520_ID import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1600_6_12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1600_6_145 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1600_8_12 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1600_8_145 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1600ID_4_15 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1660_4_155 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_1660ID_4_155 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2400_10 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2400_16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2400_L import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2600_12_165 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2600_12_185 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2600_20_165 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2600ID_8_200 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_2600ID_15_185 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4400_45_M94A import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4400_60 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4400_L30_M2000 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4600_20_250 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4600_40_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4600_45_205 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_4600_60_205 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5400_22 import * # d5 & theta5 = 35* & theta6 = -70*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5500_23 import * # d2, d5 & theta5 = 35* & theta6 = -70*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5500_27 import * # d2, d5 & theta5 = 35* & theta6 = -70*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5710_90_27 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5710_110_23 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_5720_180_26 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6400_24_120 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6400_28_120 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6400R_28_200 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6400R_25_150 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6600_175_28 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6600_225_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6620_150_22 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640_130_32 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640_180_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640_185_28 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640_205_275 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640_235_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640ID_170_275 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6640ID_200_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6650_125_32 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6650S_90_39 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6650S_125_35 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6650S_200_30 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6660_130_31 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6660_205_19 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_150_320_LeanID import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_150_320 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_155_285 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_175_305 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_200_260 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_205_280 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_235_265 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_245_300_SpotPack import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_245_300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_6700_300_270 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_150_35 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_325_31 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_340_28 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_400_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_500_230 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_7600_500_255 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_8700_550_420 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.ABB_IRB_8700_800_350 import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_iisy_3_R760 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_iisy_3_R930 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_iisy_3_R1300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR3_R540 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR4_R600 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR5_arc_HW import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR5_arc import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR5_sixx_R650 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR5_sixx_R850 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_2_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_arc import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R700_sixx import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R700_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R900_sixx import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R900 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R900_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R1820_Cybertech import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR8_R1420_arc_HW import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR8_R1620_HP import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR8_R2010 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR8_R2100_2_Arc_HW import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R900_sixx import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R900_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R1100_sixx import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R1100_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R1420 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR10_R1440_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR12_1810_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_2_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_arc_HW import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_AV300 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_L6_2_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_L6 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_L8_arc_HW import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_R1610 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR16_R2010 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR20_R1810 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR20_R3100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR22_R1610 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR30_4_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR30_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR30_L16 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR30_R2100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR30_3 import * # d2
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR45_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR50_R2100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR50_R2500 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_4_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_L16_KS import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_L30_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_L45_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR60_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR70_R2100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR90_R2700_pro import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR90_R2900_extra_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR90_R3100_extra_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR90_R3100_extra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR90_R3700_K_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR100_R3500_press import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR100_2_P import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R1800_nano import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R2500_pro import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R2700_extra_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R2700_HA import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R2700_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R2900_extra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R3100_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R3500_K_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R3500_press import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R3900_K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR120_R3900_2K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR125_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR140_comp import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_L110 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_L120_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_R2700_extra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_R3100_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_R3300_K_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_R3700_K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR150_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR160_R1570_nano import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR180_R2100_nano_F_exclusive import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR180_R2500_extra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR180_R2900_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR180_R3100_K_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR180_R3500_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR200_comp import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR200_L140_comp import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR200_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_L100_2_K import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_L150_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_L180_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R2700_extra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R2700_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R2700_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R2900_K_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R3100_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_R3300_K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_2_3100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR210_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_L180_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_L210_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R2500_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R2700_prime import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R2900_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R2900_2_F import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R3100_K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_R3330 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR240_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR250_R2700_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR270_R2700_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR270_R2900_K_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR280_R3080 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR300_R2500_ultra import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR300_R2700_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR340_R3330 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR360_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR360_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR360_L240_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR360_L280_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR360_R2830 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR480_R3330_MT_F_K import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR480_R3330_MT_F import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR480_R3400_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_L340_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_L340_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_L420_3 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_L420_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_R2800_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR500_R2830 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR510_R3080 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR560_R3100_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR600_R2830 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR800_R2800_2 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR1000_L750_titan import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR1000_titan import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.KUKA_KR6_R1840_2 import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_AR2010 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_AR3120 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_DX1350D import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_EA1400 import * # a6, theta5 = 90*, Has margin of error / is inprecise
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_EH80 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_EPX2050 import * # d5, theta5=60* & theta6=-60*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_EPX2800R import * # d5, theta5=60* & theta6=-60*
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_ES165D import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_ES165D_100 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_ES165RD import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_ES200D import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_ES200N import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_GA50 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_GP20 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_GP200R import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_GP225 import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Motoman_HP6 import * # theta5 = 90*

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Yaskawa_HC10 import * # d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Yaskawa_HC10DTP import * # d2 & d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Yaskawa_HC20DTP import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Yaskawa_MotoMINI import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Yaskawa_GP7 import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Automata_EVA import * # a6

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Annin_Robotics_AR2 import * # d2

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Fanuc_CRX_20iAL import * # d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Fanuc_ARC_Mate_100iD_8L import *
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Fanuc_LR_Mate_200iC import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Hans_E03 import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.Hanwha_HCR12 import *

from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.TM25S import * # d2 & d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.TM25SX import * # d2 & d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.TM30S import * # d2 & d5
from robotkinematicscatalogue.inversekinematics.__6DOF.__industrialRobots.TM30SX import * # d2 & d5